apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-controller-config
  namespace: default
data:
  cpuThreshold: "0.05"
  restartThreshold: "3"

  nodeCPUThreshold: "0.80"
  nodeMemoryThreshold: "0.85"