apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: dummy-app:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080